name: "CI" # Note that this name appears in the README's badge
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # This match the tox envs possible, so we can deliberately invoke every one
          - python-version: "3.6"
            django-tox-env: "django22"
          - python-version: "3.7"
            django-tox-env: "django22"
          - python-version: "3.8"
            django-tox-env: "django22"
          - python-version: "3.9"
            django-tox-env: "django22"

          - python-version: "3.7"
            django-tox-env: "django32"
          - python-version: "3.8"
            django-tox-env: "django32"
          - python-version: "3.9"
            django-tox-env: "django32"
          - python-version: "3.10"
            django-tox-env: "django32"

          - python-version: "3.8"
            django-tox-env: "django40"
          - python-version: "3.9"
            django-tox-env: "django40"
          - python-version: "3.10"
            django-tox-env: "django40"

    name: Python ${{ matrix.python-version }} in use with ${{ matrix.django-tox-env }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # Note that all envs will have the default version of Python available,
          # too. This is 3.8 at time of writing.
          python-version: ${{ matrix.python-version }}
          architecture: "x64" # optional x64 (default) or x86.
      - name: Install test requirements
        run: pip install -r requirements_test.txt
      - name: Run tox
        run: tox -e py${{ matrix.python-version }}-${{ matrix.django-tox-env }}

  lint:
    runs-on: ubuntu-latest
    name: Flake 8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install test requirements
        run: pip install -r requirements_test.txt
      - name: Run tox
        run: tox -e py3.9-flake8
